// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrMJ91lLKNXcNHg6iO8vthLUp7JQrqz60',
    appId: '1:786525392712:web:a1fe81edd7ae712b47ed7d',
    messagingSenderId: '786525392712',
    projectId: 'esengulnotlarim',
    authDomain: 'esengulnotlarim.firebaseapp.com',
    storageBucket: 'esengulnotlarim.appspot.com',
    measurementId: 'G-6PFQPKTD45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyet76iQcI_MuSCYzg3UZb6jRa8ZMjcW0',
    appId: '1:786525392712:android:5ca64a94a87bee5847ed7d',
    messagingSenderId: '786525392712',
    projectId: 'esengulnotlarim',
    storageBucket: 'esengulnotlarim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2n_B4zVGSNsIjxEMcBtHp1eGmRTaO4mE',
    appId: '1:786525392712:ios:60887a75020c926547ed7d',
    messagingSenderId: '786525392712',
    projectId: 'esengulnotlarim',
    storageBucket: 'esengulnotlarim.appspot.com',
    iosClientId:
        '786525392712-fcg4s74mu653m0tha7as652fv70l0t0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.esengulnotlar',
  );
}
